### ISSUE TITLE
NameError: name 'P' is not defined

### ISSUE THREAD

**Issue by wen10-git** [ShiuLab/PseudogenePipeline#11]
Hello, @shinhanshiu 
I have encountered some problems. The error is reported below. My running process can be roughly referred to (in Chinese): https://yanzhongsino.github.io/2022/09/07/bioinfo_pseudogene_PseudogenePipeline/

```
(ge) w@w:~/w2/HIFI1/juicer/3d-dna-review1-3/pseudo/pseudo1$ python ~/tool/PseudogenePipeline-master/_scripts/PseudogenePipeline.py parameter_file 
here
#### Step 0: read, check, and set parameters
Check parameter file...
Check names among genome/protein seq, and blast output
WARNING: Blast output not fully covered by genome/protein seq
Protein coverage: 0.0
Contig coverage: 1.0
The coverage problem appears to be due to the use of space characters in protein and contig names: BLAST truncates protein and contig names containg space.
Temporary copies of the genome and protein sequence file will be made using truncated names. The original names will be restored in the final ouput GFF file.
Traceback (most recent call last):
  File "/home/w/tool/PseudogenePipeline-master/_scripts/PseudogenePipeline.py", line 640, in <module>
    main()
  File "/home/w/tool/PseudogenePipeline-master/_scripts/PseudogenePipeline.py", line 344, in main
    mismatch_status = check_seq_names(P["p_seq"], P["g_seq"], P["b_out"]) 
  File "/home/w/tool/PseudogenePipeline-master/_scripts/PseudogenePipeline.py", line 281, in check_seq_names
    "python %s/TruncateGeneNames.py %s" % (P["p_codes"],P["p_seq"]))
NameError: name 'P' is not defined
```

[parameter_file.txt](https://github.com/ShiuLab/PseudogenePipeline/files/11858510/parameter_file.txt)

**Comment by wen10-git** [comment]
Resolved, I found spaces in the protein names.
